### ISSUE TITLE
Tutorial skip button only skips current level in tutorial

### ISSUE THREAD

**Issue by yonomitt** [abregado/broadstories#7]
Should it skip the entire tutorial?

**Comment by abregado** [comment]
No, it should just skip the next level (so you can get to Endless mode faster or continue from a later tutorial level if the game crashes)

**Comment by yonomitt** [comment]
How about a user setting that saves which tutorials have been completed or skipped, so the "pro" user doesn't have to skip through all 6 tutorials each time he/she opens the game?

**Comment by abregado** [comment]
I had considered this but decided it was not critical for the release. As the majority of use cases will be player playing it once through and then handing it to someone else. Most likely when I tweak the mod loader Ill have it load an empty level queue if you have no mods installed, which effectivly skips the tutorial (Tutorials are imported just like mod levels)

**Comment by yonomitt** [comment]
Fair enough. That makes sense for a prototype.
